import type { ThemeTokens } from '@sat-sys/ui';

export interface ThemePreset {
  name: string;
  description: string;
  tokens: Partial<ThemeTokens>;
}

/**
 * Curated one-click theme presets.
 *
 * The default preset keeps an empty override set so it resolves, through
 * `resolveThemeConfig`, to the canonical baseline brand. The remaining five
 * presets supply a coherent set of brand + surface + navigation + table
 * tokens so choosing one meaningfully restyles the whole POS. Any token left
 * unset still falls back to `DEFAULT_TOKENS`.
 */
export const THEME_PRESETS: ThemePreset[] = [
  {
    name: 'Brand Orange',
    description: 'Default enterprise theme',
    tokens: {},
  },
  {
    name: 'Midnight Blue',
    description: 'Calm, trustworthy navy',
    tokens: {
      primary: '#2563eb',
      accent: '#2563eb',
      secondary: '#0f172a',
      background: '#f8fafc',
      backgroundSecondary: '#f1f5f9',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
      border: '#e2e8f0',
      cardBackground: '#ffffff',
      cardBorder: '#e2e8f0',
      cardHeader: '#f8fafc',
      sidebarBackground: '#0f172a',
      sidebarForeground: '#94a3b8',
      sidebarHover: '#1e293b',
      sidebarActive: '#2563eb',
      navbarBackground: '#ffffff',
      navbarBorder: '#e2e8f0',
      buttonPrimary: '#2563eb',
      inputFocus: '#2563eb',
      tableHeader: '#f1f5f9',
      tableHeaderText: '#475569',
      info: '#2563eb',
      chart1: '#3b82f6',
    },
  },
  {
    name: 'Emerald',
    description: 'Fresh, growth-inspired green',
    tokens: {
      primary: '#059669',
      accent: '#059669',
      secondary: '#064e3b',
      background: '#f0fdf4',
      backgroundSecondary: '#dcfce7',
      surface: '#ffffff',
      surfaceHover: '#f0fdf4',
      textPrimary: '#022c22',
      textSecondary: '#065f46',
      textMuted: '#047857',
      border: '#bbf7d0',
      cardBackground: '#ffffff',
      cardBorder: '#bbf7d0',
      cardHeader: '#f0fdf4',
      sidebarBackground: '#022c22',
      sidebarForeground: '#a7f3d0',
      sidebarHover: '#064e3b',
      sidebarActive: '#10b981',
      navbarBorder: '#bbf7d0',
      buttonPrimary: '#059669',
      inputFocus: '#059669',
      tableHeader: '#dcfce7',
      tableHeaderText: '#065f46',
      success: '#059669',
      chart4: '#10b981',
    },
  },
  {
    name: 'Royal Purple',
    description: 'Rich, sophisticated violet',
    tokens: {
      primary: '#7c3aed',
      accent: '#7c3aed',
      secondary: '#2e1065',
      background: '#faf5ff',
      backgroundSecondary: '#f3e8ff',
      surface: '#ffffff',
      surfaceHover: '#faf5ff',
      textPrimary: '#2e1065',
      textSecondary: '#6b21a8',
      textMuted: '#7e22ce',
      border: '#e9d5ff',
      cardBackground: '#ffffff',
      cardBorder: '#e9d5ff',
      cardHeader: '#faf5ff',
      sidebarBackground: '#2e1065',
      sidebarForeground: '#d8b4fe',
      sidebarHover: '#4c1d95',
      sidebarActive: '#a855f7',
      navbarBorder: '#e9d5ff',
      buttonPrimary: '#7c3aed',
      inputFocus: '#a855f7',
      tableHeader: '#f3e8ff',
      tableHeaderText: '#6b21a8',
      chart3: '#8b5cf6',
    },
  },
  {
    name: 'Rose',
    description: 'Warm, inviting crimson',
    tokens: {
      primary: '#e11d48',
      accent: '#e11d48',
      secondary: '#4c0519',
      background: '#fff1f2',
      backgroundSecondary: '#ffe4e6',
      surface: '#ffffff',
      surfaceHover: '#fff1f2',
      textPrimary: '#4c0519',
      textSecondary: '#9f1239',
      textMuted: '#be123c',
      border: '#fecdd3',
      cardBackground: '#ffffff',
      cardBorder: '#fecdd3',
      cardHeader: '#fff1f2',
      sidebarBackground: '#4c0519',
      sidebarForeground: '#fda4af',
      sidebarHover: '#881337',
      sidebarActive: '#e11d48',
      navbarBorder: '#fecdd3',
      buttonPrimary: '#e11d48',
      inputFocus: '#fb7185',
      tableHeader: '#ffe4e6',
      tableHeaderText: '#9f1239',
      danger: '#e11d48',
      chart5: '#ef4444',
    },
  },
  {
    name: 'Slate',
    description: 'Clean, monochrome minimal',
    tokens: {
      primary: '#334155',
      accent: '#334155',
      secondary: '#0f172a',
      background: '#f8fafc',
      backgroundSecondary: '#f1f5f9',
      surface: '#ffffff',
      surfaceHover: '#f1f5f9',
      textPrimary: '#0f172a',
      textSecondary: '#475569',
      textMuted: '#64748b',
      border: '#e2e8f0',
      cardBackground: '#ffffff',
      cardBorder: '#e2e8f0',
      cardHeader: '#f8fafc',
      sidebarBackground: '#0f172a',
      sidebarForeground: '#cbd5e1',
      sidebarHover: '#1e293b',
      sidebarActive: '#334155',
      navbarBorder: '#e2e8f0',
      buttonPrimary: '#334155',
      inputFocus: '#64748b',
      tableHeader: '#f1f5f9',
      tableHeaderText: '#475569',
      chart1: '#475569',
      chart2: '#64748b',
    },
  },
];