import type { ResolvedTheme, ThemeTokens } from './types';

/**
 * Baseline token values.
 *
 * These intentionally mirror the current hard-coded design language of the
 * POS (Tailwind gray palette, brand orange #ff6600, dark sidebar #1A1A1A,
 * etc.) so that the default theme is pixel-identical to the existing UI.
 * No page is changed by this file; it only establishes the fallback values.
 */
export const DEFAULT_TOKENS: ThemeTokens = {
  background: '#f9fafb',
  backgroundSecondary: '#f3f4f6',
  surface: '#ffffff',
  surfaceSecondary: '#f9fafb',
  surfaceHover: '#f3f4f6',
  textPrimary: '#111827',
  textSecondary: '#4b5563',
  textMuted: '#6b7280',
  textInverse: '#ffffff',
  primary: '#ff6600',
  primaryHover: '#e55c00',
  primaryActive: '#cc5200',
  primaryForeground: '#ffffff',
  secondary: '#1a1a1a',
  secondaryHover: '#333333',
  secondaryForeground: '#ffffff',
  accent: '#ff6600',
  success: '#16a34a',
  warning: '#d97706',
  danger: '#dc2626',
  info: '#2563eb',
  border: '#e5e7eb',
  borderLight: '#f3f4f6',
  divider: '#e5e7eb',
  cardBackground: '#ffffff',
  cardBorder: '#e5e7eb',
  cardHeader: '#f9fafb',
  sidebarBackground: '#1A1A1A',
  sidebarForeground: '#B8B6B0',
  sidebarHover: '#252525',
  sidebarActive: '#ff6600',
  sidebarBorder: '#252525',
  navbarBackground: '#ffffff',
  navbarForeground: '#1a1a1a',
  navbarBorder: '#e5e7eb',
  buttonPrimary: '#ff6600',
  buttonSecondary: '#ffffff',
  buttonDanger: '#dc2626',
  buttonOutline: '#ffffff',
  buttonGhost: 'transparent',
  inputBackground: '#ffffff',
  inputBorder: '#d1d5db',
  inputText: '#111827',
  inputPlaceholder: '#9ca3af',
  inputFocus: '#3b82f6',
  tableHeader: '#f3f4f6',
  tableHeaderText: '#4b5563',
  tableRow: '#ffffff',
  tableHover: '#f9fafb',
  tableSelected: '#eff6ff',
  tableBorder: '#e5e7eb',
  badgeSuccess: '#16a34a',
  badgeWarning: '#d97706',
  badgeDanger: '#dc2626',
  badgeInfo: '#2563eb',
  badgeDefault: '#6b7280',
  chart1: '#3b82f6',
  chart2: '#f59e0b',
  chart3: '#8b5cf6',
  chart4: '#10b981',
  chart5: '#ef4444',
  chartGrid: '#e5e7eb',
  receiptBackground: '#ffffff',
  receiptBorder: '#e5e7eb',
  receiptText: '#111827',
  orderStatus: {
    draft: '#6b7280',
    pending: '#2563eb',
    preparing: '#d97706',
    ready: '#16a34a',
    completed: '#6b7280',
    cancelled: '#dc2626',
    paid: '#16a34a',
    refunded: '#dc2626',
  },
  inventoryStatus: {
    healthy: '#16a34a',
    lowStock: '#f59e0b',
    critical: '#ef4444',
  },
};

export const DEFAULT_BRANDING = {
  restaurantName: undefined as string | undefined,
  restaurantLogo: undefined as string | undefined,
  dashboardLogo: undefined as string | undefined,
  receiptLogo: undefined as string | undefined,
  loginLogo: undefined as string | undefined,
  brandFont: undefined as string | undefined,
  accentColor: undefined as string | undefined,
};

export const DEFAULT_THEME: ResolvedTheme = {
  ...DEFAULT_TOKENS,
  ...DEFAULT_BRANDING,
};
